{
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-darwin" "aarch64-linux" ] (system:
      let
        pkgs = import nixpkgs { inherit system; };
        inherit (pkgs) stdenv mkShell;
        fixed-output-hashes = {
          x86_64-linux = "sha256-raBq1sk8j+Bdl6ZLHH5bf1+4qEtq6uRoSE9t3ddqGTA=";
          aarch64-darwin = "sha256-6/dJYZZFnXbBkpDelMzbAVFv8tMOLkEhDwOLyer2G+Y=";
          aarch64-linux = "sha256-45OU14f03w2dFR7JgEftzijW93guVmCkK0YAd3jkxL0=";
        };
      in
      {
        devShells.default = mkShell {
          packages = with pkgs; [
            erlang_27
            beam27Packages.rebar3
            gleam
          ];
        };
        overlays = _: _: { gleeter = self.packages.${system}.default; };
        packages.default = stdenv.mkDerivation rec {
          pname = "gleeter";
          version = "1.1.0";

          gleamPackages = stdenv.mkDerivation {
            inherit version;
            pname = "${pname}-gleam-packages";

            nativeBuildInputs = with pkgs; [
              gleam
              beam27Packages.rebar3
            ];
            src = builtins.filterSource
              (path: _: builtins.elem (baseNameOf path) [ "manifest.toml" "gleam.toml" ]) ./.;

            buildPhase = ''
              export HOME=$PWD
              gleam deps download
              grep -v '\[packages\]' build/packages/packages.toml | sort > packages.toml
              echo -e "[packages]\n" > build/packages/packages.toml
              cat packages.toml >> build/packages/packages.toml
              rm packages.toml

              for dep in build/packages/*; do
                if test -d $dep; then
                  pushd $dep
                  rebar3 get-deps
                  rm -fr _build
                  popd
                fi
              done

              # This is a horrible hack to fix the packages.idx file generated by rebar3,
              # I am not sure on what this should be, but it is the only part of the file
              # which differs at each build. Setting it to a fixed value solves the issue.
              # The fixed value has been retrieved during one of the failed builds.
              printf "\x00\xef\x86\xde\x62\x00\x01\xd3\x6b\xcf\x07\x68\x02\x77\x16\x64" | dd of=.cache/rebar3/hex/packages.idx seek=48 bs=1 conv=notrunc
            '';

            installPhase = ''
              runHook preInstallHook
              mkdir -p $out
              cp --recursive build $out/
              cp --recursive $PWD/.cache $out/
              runHook postInstallHook
            '';

            outputHashAlgo = "sha256";
            outputHashMode = "recursive";
            outputHash = fixed-output-hashes.${system};
          };

          src = builtins.filterSource
            (path: _: ! builtins.elem (baseNameOf path) [ "build" ".git" ".direnv" ".envrc" ])
            ./.;

          nativeBuildInputs = with pkgs; [
            gleam
            rebar3
            gleamPackages
          ];

          buildInputs = with pkgs; [
            erlang_27
          ];

          doCheck = true;

          configurePhase = ''
            cp --recursive ${gleamPackages}/build .
            cp --recursive ${gleamPackages}/.cache .
            chmod -R 0755 build
          '';

          checkPhase = ''
            HOME=$PWD make test
          '';

          buildPhase = ''
            runHook preBuildHook
            HOME=$PWD gleam export erlang-shipment
            runHook postBuildHook
          '';

          installPhase = ''
            runHook preInstallHook
            mkdir -p $out/opt/gleeter/
            mkdir -p $out/bin/
            cp -r build/erlang-shipment/* $out/opt/gleeter/
            substituteInPlace $out/opt/gleeter/entrypoint.sh \
              --replace erl ${pkgs.erlang_27}/bin/erl
            cp scripts/gleeter $out/bin/gleeter
            substituteInPlace $out/bin/gleeter \
              --replace /opt/gleeter $out/opt/gleeter
            runHook postInstallHook
          '';

          meta = with pkgs.lib; {
            description = "Fetch and display XKCD comics directly in the terminal";
            mainProgram = "gleeter";
            homepage = "https://github.com/massix/gleeter";
            license = licenses.mit;
            maintainers = [ maintainers.massimogengarelli ];
          };
        };
        app.default = self.packages.default;
      });
}
