name = "gleeter"
version = "1.0.0"
description = "Show XKCD comics right in your terminal!"
licenses = ["MIT"]
repository = { type = "github", user = "massix", repo = "gleeter" }

[dependencies]
gleam_stdlib = "0.39.0"
gleam_hackney = "1.2.0"
gleam_json = "2.0.0"
gleam_erlang = "0.25.0"
gleam_otp = "0.10.0"
birl = "1.7.1"
simplifile = "2.0.1"
gleam_http = "3.6.0"
argv = "1.0.2"

[dev-dependencies]
startest = "0.5.0"
