global:
  scrape_interval: "10s"
  scrape_timeout: "10s"
scrape_configs:
  - job_name: gleeter
    metrics_path: /comics/metrics
    honor_labels: true
    scheme: http
    follow_redirects: true
    static_configs:
      - targets: ['gleeter:9999']
        labels:
          instance: gleeter
          platform: docker
