name: Build and push Docker image
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        os_version: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nicknovitski/nix-develop@v1
      - run: make docker
      - run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u massix86 --password-stdin
          docker push massix86/gleeter:latest
          docker push "massix86/gleeter:$(cat result)"
