name: Unit tests and nix build
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      nix_build:
        description: Nix build
        type: boolean
        default: true
        required: true
      run_tests:
        description: Run unit tests
        type: boolean
        default: false
        required: true
      build_docker:
        description: Build docker image
        type: boolean
        default: false
        required: true
      check_format:
        description: Check formatting
        type: boolean
        default: false
        required: true
jobs:
  nix-build:
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        os_version: [ubuntu-24.04, macos-15, ubuntu-24.04-arm]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nicknovitski/nix-develop@v1
      - run: nix build . --print-build-logs
      - run: result/bin/gleeter version
    if: ${{ inputs.nix_build || true }}
  unit-test:
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        os_version: [ubuntu-24.04, macos-15, ubuntu-24.04-arm]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nicknovitski/nix-develop@v1
      - run: make test
    if: ${{ inputs.run_tests || true }}
  check-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nicknovitski/nix-develop@v1
      - run: make check-format
    if: ${{ inputs.check_format || true }}
  build-docker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nicknovitski/nix-develop@v1
      - run: make docker
      - run: docker run --rm massix/gleeter:latest
    if: ${{ inputs.build_docker || true }}
